import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useMemo } from "react";
import { useMatchResults } from "../../hooks/useMatchResults";
export var RecruiterSearchResultsPage = function () {
    var matchQuery = useMemo(function () { return ({
        roleDescriptor: {
            title: "Frontend Lead",
            description: "Build recruiter portal UX for KnowTruly.",
            requiredSkills: ["React", "TypeScript", "Design Systems"]
        },
        topK: 5
    }); }, []);
    var _a = useMatchResults({ query: matchQuery }), matchResults = _a.data, isLoading = _a.isLoading;
    return (_jsxs("section", { className: "space-y-6", children: [_jsxs("header", { children: [_jsx("h1", { className: "text-2xl font-semibold text-slate-100", children: "Search Results Overview" }), _jsx("p", { className: "mt-2 text-sm text-slate-400", children: "Hybrid scores combine embedding similarity and rules (weights 0.7 / 0.3). Scores above 0.8 usually indicate excellent fit." })] }), _jsx("div", { className: "rounded-2xl border border-slate-800 bg-[#0f141c] p-6", children: _jsxs("div", { className: "flex flex-col gap-2 md:flex-row md:items-center md:justify-between", children: [_jsxs("p", { className: "text-sm text-slate-300", children: ["Query embedding: ", _jsx("span", { className: "font-mono text-xs text-slate-500", children: matchResults === null || matchResults === void 0 ? void 0 : matchResults.queryEmbeddingId })] }), _jsxs("p", { className: "text-xs uppercase tracking-[0.2em] text-slate-500", children: ["Matched at ", matchResults && new Date(matchResults.matchedAt).toLocaleString()] })] }) }), _jsxs("div", { className: "space-y-4", children: [isLoading && _jsx("p", { className: "text-sm text-slate-400", children: "Loading match results..." }), matchResults === null || matchResults === void 0 ? void 0 : matchResults.matches.map(function (match) { return (_jsxs("article", { className: "rounded-2xl border border-slate-800 bg-[#0f141c] p-6", children: [_jsxs("div", { className: "flex flex-wrap items-center justify-between gap-4", children: [_jsxs("div", { children: [_jsx("p", { className: "text-lg font-semibold text-slate-100", children: match.candidateId }), _jsxs("p", { className: "text-xs text-slate-500", children: ["Score ", (match.score * 100).toFixed(0), "% \u00B7 Matched ", new Date(match.matchedAt).toLocaleDateString()] })] }), _jsx("div", { className: "flex items-center gap-2", children: match.explanation.topMatchingSkills.map(function (skill) { return (_jsxs("span", { className: "rounded-full bg-sky-500/10 px-3 py-1 text-xs text-sky-300", children: [skill.skill, " ", (skill.confidence * 100).toFixed(0), "%"] }, skill.skill)); }) })] }), match.explanation.gaps.length > 0 && (_jsxs("p", { className: "mt-4 text-xs text-amber-300", children: ["Gaps: ", match.explanation.gaps.join(", ")] })), _jsxs("div", { className: "mt-4 text-xs text-slate-400", children: [_jsx("p", { className: "uppercase tracking-[0.3em] text-slate-500", children: "Evidence" }), _jsx("ul", { className: "mt-2 space-y-1", children: match.explanation.topEvidence.map(function (evidence) { return (_jsxs("li", { children: [evidence.type, " \u00B7 ", evidence.id, " \u00B7 ", (evidence.relevance * 100).toFixed(0), "% relevance"] }, "".concat(match.candidateId, "-").concat(evidence.id))); }) })] })] }, match.candidateId)); })] })] }));
};
