import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useProfile } from "../../hooks/useProfile";
export var ProfileExperiencePage = function () {
    var profile = useProfile().data;
    return (_jsxs("section", { className: "space-y-6", children: [_jsxs("header", { children: [_jsx("h1", { className: "text-2xl font-semibold text-slate-100", children: "Experience" }), _jsx("p", { className: "mt-2 text-sm text-slate-400", children: "Highlight quantified outcomes so the matchmaker can surface the right projects and claims." })] }), _jsxs("div", { className: "space-y-4", children: [profile === null || profile === void 0 ? void 0 : profile.positions.map(function (position) {
                        var _a, _b;
                        return (_jsxs("article", { className: "rounded-2xl border border-slate-800 bg-[#0f141c] p-6", children: [_jsxs("div", { className: "flex flex-wrap items-center justify-between gap-2", children: [_jsxs("div", { children: [_jsx("p", { className: "text-lg font-semibold text-slate-100", children: position.title }), _jsx("p", { className: "text-sm text-slate-400", children: position.company })] }), _jsxs("p", { className: "text-xs uppercase tracking-[0.25em] text-slate-500", children: [position.startDate, " \u2013 ", (_a = position.endDate) !== null && _a !== void 0 ? _a : "Present"] })] }), _jsx("p", { className: "mt-3 text-sm text-slate-300", children: position.description }), _jsx("div", { className: "mt-4 flex flex-wrap gap-2 text-xs", children: (_b = position.skillsUsed) === null || _b === void 0 ? void 0 : _b.map(function (skill) { return (_jsx("span", { className: "rounded-full bg-slate-800 px-3 py-1 text-slate-300", children: skill }, skill)); }) })] }, position.id));
                    }), !(profile === null || profile === void 0 ? void 0 : profile.positions.length) && (_jsx("p", { className: "rounded-2xl border border-dashed border-slate-800 bg-[#0d1219] p-6 text-center text-sm text-slate-500", children: "No positions yet. Use the API to seed demo data or connect the backend to populate this list." }))] })] }));
};
