import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useProfile } from "../../hooks/useProfile";
export var ProfileProjectsPage = function () {
    var profile = useProfile().data;
    return (_jsxs("section", { className: "space-y-6", children: [_jsxs("header", { children: [_jsx("h1", { className: "text-2xl font-semibold text-slate-100", children: "Projects" }), _jsx("p", { className: "mt-2 text-sm text-slate-400", children: "Projects connect to resume sections, recruiter previews, and signature requests. Include metrics for stronger evidence." })] }), _jsxs("div", { className: "space-y-4", children: [profile === null || profile === void 0 ? void 0 : profile.projects.map(function (project) {
                        var _a, _b;
                        return (_jsxs("article", { className: "rounded-2xl border border-slate-800 bg-[#0f141c] p-6", children: [_jsxs("div", { className: "flex flex-col gap-2 md:flex-row md:items-center md:justify-between", children: [_jsxs("div", { children: [_jsx("h2", { className: "text-lg font-semibold text-slate-100", children: project.title }), _jsx("p", { className: "text-sm text-slate-400", children: project.roleDescription })] }), _jsxs("p", { className: "text-xs uppercase tracking-[0.3em] text-slate-500", children: [project.startDate, " \u2013 ", (_a = project.endDate) !== null && _a !== void 0 ? _a : "Present"] })] }), _jsx("div", { className: "mt-4 flex flex-wrap gap-2 text-xs", children: (_b = project.technologies) === null || _b === void 0 ? void 0 : _b.map(function (tech) { return (_jsx("span", { className: "rounded-full bg-slate-800 px-3 py-1 text-slate-300", children: tech }, tech)); }) }), project.metrics && (_jsx("div", { className: "mt-4 grid gap-2 text-xs text-slate-400", children: Object.entries(project.metrics).map(function (_a) {
                                        var key = _a[0], value = _a[1];
                                        return (_jsxs("div", { className: "flex items-center justify-between rounded-lg border border-slate-800 bg-slate-900/40 px-3 py-2", children: [_jsx("span", { className: "uppercase tracking-[0.3em] text-slate-500", children: key }), _jsx("span", { className: "text-slate-200", children: value })] }, key));
                                    }) })), project.artifacts && (_jsx("div", { className: "mt-4 flex flex-wrap gap-3 text-xs text-sky-300", children: project.artifacts.map(function (artifact) { return (_jsx("a", { href: artifact, className: "underline", target: "_blank", rel: "noreferrer", children: artifact }, artifact)); }) }))] }, project.id));
                    }), !(profile === null || profile === void 0 ? void 0 : profile.projects.length) && (_jsx("p", { className: "rounded-2xl border border-dashed border-slate-800 bg-[#0d1219] p-6 text-center text-sm text-slate-500", children: "No projects recorded yet. Add them via the API to showcase evidence-driven impact." }))] })] }));
};
