import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useProfile } from "../../hooks/useProfile";
export var ProfileSkillsPage = function () {
    var _a, _b;
    var profile = useProfile().data;
    var verifiedSkills = (_a = profile === null || profile === void 0 ? void 0 : profile.skills.filter(function (skill) { return skill.verified; })) !== null && _a !== void 0 ? _a : [];
    var unverifiedSkills = (_b = profile === null || profile === void 0 ? void 0 : profile.skills.filter(function (skill) { return !skill.verified; })) !== null && _b !== void 0 ? _b : [];
    return (_jsxs("section", { className: "space-y-6", children: [_jsxs("header", { children: [_jsx("h1", { className: "text-2xl font-semibold text-slate-100", children: "Skills & Verification" }), _jsx("p", { className: "mt-2 text-sm text-slate-400", children: "Verified skills link to claims and boost match confidence. Use the signature service to verify new evidence." })] }), _jsxs("div", { className: "grid gap-6 md:grid-cols-2", children: [_jsxs("div", { className: "rounded-2xl border border-emerald-500/40 bg-emerald-500/5 p-6", children: [_jsx("h2", { className: "text-lg font-semibold text-emerald-200", children: "Verified skills" }), _jsxs("div", { className: "mt-4 flex flex-wrap gap-2 text-xs", children: [verifiedSkills.map(function (skill) { return (_jsxs("span", { className: "rounded-full border border-emerald-500/30 bg-emerald-500/10 px-3 py-1 text-emerald-100", children: [skill.name, " \u00B7 ", skill.proficiency] }, skill.id)); }), !verifiedSkills.length && _jsx("p", { className: "text-sm text-emerald-100/70", children: "No verified skills yet." })] })] }), _jsxs("div", { className: "rounded-2xl border border-slate-800 bg-[#0f141c] p-6", children: [_jsx("h2", { className: "text-lg font-semibold text-slate-100", children: "Skills to verify" }), _jsxs("div", { className: "mt-4 flex flex-wrap gap-2 text-xs text-slate-300", children: [unverifiedSkills.map(function (skill) { return (_jsxs("span", { className: "rounded-full bg-slate-800 px-3 py-1", children: [skill.name, " \u00B7 ", skill.proficiency] }, skill.id)); }), !unverifiedSkills.length && _jsx("p", { className: "text-sm text-slate-500", children: "All tracked skills are currently verified." })] })] })] })] }));
};
