import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useProfile } from "../../hooks/useProfile";
export var ProfileEducationPage = function () {
    var profile = useProfile().data;
    return (_jsxs("section", { className: "space-y-6", children: [_jsxs("header", { children: [_jsx("h1", { className: "text-2xl font-semibold text-slate-100", children: "Education" }), _jsx("p", { className: "mt-2 text-sm text-slate-400", children: "Education entries feed both resume generation and recruiter match explanations." })] }), _jsx("div", { className: "overflow-hidden rounded-2xl border border-slate-800", children: _jsxs("table", { className: "min-w-full divide-y divide-slate-800 text-sm", children: [_jsx("thead", { className: "bg-[#0f1623] text-xs uppercase tracking-[0.2em] text-slate-500", children: _jsxs("tr", { children: [_jsx("th", { className: "px-4 py-3 text-left", children: "Institution" }), _jsx("th", { className: "px-4 py-3 text-left", children: "Degree" }), _jsx("th", { className: "px-4 py-3 text-left", children: "Field" }), _jsx("th", { className: "px-4 py-3 text-left", children: "Timeline" }), _jsx("th", { className: "px-4 py-3 text-left", children: "Achievements" })] }) }), _jsxs("tbody", { className: "divide-y divide-slate-900 bg-[#0d1219] text-slate-300", children: [profile === null || profile === void 0 ? void 0 : profile.education.map(function (entry) {
                                    var _a, _b, _c;
                                    return (_jsxs("tr", { className: "hover:bg-slate-900/40", children: [_jsx("td", { className: "px-4 py-4 text-slate-100", children: _jsx("p", { className: "font-semibold", children: entry.institution }) }), _jsx("td", { className: "px-4 py-4", children: entry.degree }), _jsx("td", { className: "px-4 py-4", children: entry.fieldOfStudy }), _jsxs("td", { className: "px-4 py-4 text-xs text-slate-400", children: [entry.startDate, " \u2013 ", (_a = entry.endDate) !== null && _a !== void 0 ? _a : "Present"] }), _jsx("td", { className: "px-4 py-4 text-xs text-slate-400", children: (_c = (_b = entry.achievements) === null || _b === void 0 ? void 0 : _b.join(", ")) !== null && _c !== void 0 ? _c : "—" })] }, entry.id));
                                }), !(profile === null || profile === void 0 ? void 0 : profile.education.length) && (_jsx("tr", { children: _jsx("td", { colSpan: 5, className: "px-4 py-6 text-center text-slate-500", children: "No education data yet. Add entries via the API to see them reflected here." }) }))] })] }) })] }));
};
