import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useAuthStore } from "../../stores/authStore";
import { useConfigStore } from "../../stores/configStore";
export var SettingsPage = function () {
    var _a;
    var user = useAuthStore(function (state) { return state.user; });
    var _b = useConfigStore(function (state) { return ({
        useDemoData: state.useDemoData,
        setUseDemoData: state.setUseDemoData
    }); }), useDemoData = _b.useDemoData, setUseDemoData = _b.setUseDemoData;
    return (_jsxs("section", { className: "space-y-6", children: [_jsxs("header", { children: [_jsx("h1", { className: "text-2xl font-semibold text-slate-100", children: "Account Settings" }), _jsx("p", { className: "mt-2 text-sm text-slate-400", children: "Manage environment flags and see current session details." })] }), _jsxs("div", { className: "grid gap-6 md:grid-cols-2", children: [_jsxs("section", { className: "rounded-2xl border border-slate-800 bg-[#0f141c] p-6", children: [_jsx("h2", { className: "text-lg font-semibold text-slate-100", children: "Session info" }), _jsxs("dl", { className: "mt-4 space-y-3 text-sm text-slate-300", children: [_jsxs("div", { children: [_jsx("dt", { className: "text-xs uppercase tracking-[0.25em] text-slate-500", children: "User" }), _jsx("dd", { children: user === null || user === void 0 ? void 0 : user.name })] }), _jsxs("div", { children: [_jsx("dt", { className: "text-xs uppercase tracking-[0.25em] text-slate-500", children: "Email" }), _jsx("dd", { children: (_a = user === null || user === void 0 ? void 0 : user.email) !== null && _a !== void 0 ? _a : "demo session" })] }), _jsxs("div", { children: [_jsx("dt", { className: "text-xs uppercase tracking-[0.25em] text-slate-500", children: "Role" }), _jsx("dd", { children: user === null || user === void 0 ? void 0 : user.role })] })] })] }), _jsxs("section", { className: "rounded-2xl border border-slate-800 bg-[#0f141c] p-6", children: [_jsx("h2", { className: "text-lg font-semibold text-slate-100", children: "Demo mode" }), _jsx("p", { className: "mt-2 text-sm text-slate-300", children: "Demo data mirrors backend responses so you can navigate the UI without an active FastAPI server. Disable to call real endpoints." }), _jsxs("label", { className: "mt-4 flex items-center gap-3 text-sm text-slate-200", children: [_jsx("input", { type: "checkbox", checked: useDemoData, onChange: function (event) { return setUseDemoData(event.target.checked); }, className: "h-4 w-4 rounded border border-slate-700 bg-slate-900 text-sky-500 focus:ring-sky-500" }), "Enable demo responses"] })] })] })] }));
};
