import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Route, Routes } from "react-router-dom";
import { DashboardLayout } from "./components/layout/DashboardLayout";
import { PublicLayout } from "./components/layout/PublicLayout";
import { ProtectedRoute } from "./components/routing/ProtectedRoute";
import { NotFoundPage } from "./pages/common/NotFoundPage";
import { AdminAnalyticsPage } from "./pages/admin/AdminAnalyticsPage";
import { AdminDashboardPage } from "./pages/admin/AdminDashboardPage";
import { AdminTemplatesPage } from "./pages/admin/AdminTemplatesPage";
import { AdminUsersPage } from "./pages/admin/AdminUsersPage";
import { IssuerClaimsPage } from "./pages/issuer/IssuerClaimsPage";
import { IssuerDashboardPage } from "./pages/issuer/IssuerDashboardPage";
import { IssuerSignPage } from "./pages/issuer/IssuerSignPage";
import { VerifySignaturePage } from "./pages/issuer/VerifySignaturePage";
import { RecruiterCandidateDetailPage } from "./pages/recruiter/CandidateDetailPage";
import { RecruiterDashboardPage } from "./pages/recruiter/RecruiterDashboardPage";
import { RecruiterRequestsPage } from "./pages/recruiter/RecruiterRequestsPage";
import { RecruiterSearchResultsPage } from "./pages/recruiter/RecruiterSearchResultsPage";
import { TalentSearchPage } from "./pages/recruiter/TalentSearchPage";
import { GenerateResumePage } from "./pages/student/GenerateResumePage";
import { ProfileEducationPage } from "./pages/student/ProfileEducationPage";
import { ProfileExperiencePage } from "./pages/student/ProfileExperiencePage";
import { ProfilePage } from "./pages/student/ProfilePage";
import { ProfileProjectsPage } from "./pages/student/ProfileProjectsPage";
import { ProfileSkillsPage } from "./pages/student/ProfileSkillsPage";
import { ResumeDashboardPage } from "./pages/student/ResumeDashboardPage";
import { ResumeDetailPage } from "./pages/student/ResumeDetailPage";
import { SettingsPage } from "./pages/student/SettingsPage";
import { StudentDashboardPage } from "./pages/student/DashboardPage";
import { VerificationPage } from "./pages/student/VerificationPage";
import { AboutPage } from "./pages/public/AboutPage";
import { LandingPage } from "./pages/public/LandingPage";
import { LoginPage } from "./pages/public/LoginPage";
import { RegisterPage } from "./pages/public/RegisterPage";
import { TemplatesPage } from "./pages/public/TemplatesPage";
var App = function () { return (_jsxs(Routes, { children: [_jsxs(Route, { element: _jsx(PublicLayout, {}), children: [_jsx(Route, { index: true, element: _jsx(LandingPage, {}) }), _jsx(Route, { path: "/about", element: _jsx(AboutPage, {}) }), _jsx(Route, { path: "/templates", element: _jsx(TemplatesPage, {}) }), _jsx(Route, { path: "/login", element: _jsx(LoginPage, {}) }), _jsx(Route, { path: "/register", element: _jsx(RegisterPage, {}) })] }), _jsx(Route, { element: _jsx(ProtectedRoute, { allowedRoles: ["student"] }), children: _jsxs(Route, { element: _jsx(DashboardLayout, {}), children: [_jsx(Route, { path: "/dashboard", element: _jsx(StudentDashboardPage, {}) }), _jsx(Route, { path: "/profile", element: _jsx(ProfilePage, {}) }), _jsx(Route, { path: "/profile/education", element: _jsx(ProfileEducationPage, {}) }), _jsx(Route, { path: "/profile/experience", element: _jsx(ProfileExperiencePage, {}) }), _jsx(Route, { path: "/profile/skills", element: _jsx(ProfileSkillsPage, {}) }), _jsx(Route, { path: "/profile/projects", element: _jsx(ProfileProjectsPage, {}) }), _jsx(Route, { path: "/resumes", element: _jsx(ResumeDashboardPage, {}) }), _jsx(Route, { path: "/resumes/generate", element: _jsx(GenerateResumePage, {}) }), _jsx(Route, { path: "/resumes/:id", element: _jsx(ResumeDetailPage, {}) }), _jsx(Route, { path: "/verification", element: _jsx(VerificationPage, {}) }), _jsx(Route, { path: "/settings", element: _jsx(SettingsPage, {}) })] }) }), _jsx(Route, { element: _jsx(ProtectedRoute, { allowedRoles: ["recruiter"] }), children: _jsxs(Route, { element: _jsx(DashboardLayout, {}), children: [_jsx(Route, { path: "/recruiter/dashboard", element: _jsx(RecruiterDashboardPage, {}) }), _jsx(Route, { path: "/recruiter/search", element: _jsx(TalentSearchPage, {}) }), _jsx(Route, { path: "/recruiter/search/results", element: _jsx(RecruiterSearchResultsPage, {}) }), _jsx(Route, { path: "/recruiter/candidates/:id", element: _jsx(RecruiterCandidateDetailPage, {}) }), _jsx(Route, { path: "/recruiter/requests", element: _jsx(RecruiterRequestsPage, {}) })] }) }), _jsx(Route, { element: _jsx(ProtectedRoute, { allowedRoles: ["issuer"] }), children: _jsxs(Route, { element: _jsx(DashboardLayout, {}), children: [_jsx(Route, { path: "/issuer/dashboard", element: _jsx(IssuerDashboardPage, {}) }), _jsx(Route, { path: "/issuer/claims", element: _jsx(IssuerClaimsPage, {}) }), _jsx(Route, { path: "/issuer/sign", element: _jsx(IssuerSignPage, {}) }), _jsx(Route, { path: "/issuer/verify/:signature_id", element: _jsx(VerifySignaturePage, {}) })] }) }), _jsx(Route, { element: _jsx(ProtectedRoute, { allowedRoles: ["admin"] }), children: _jsxs(Route, { element: _jsx(DashboardLayout, {}), children: [_jsx(Route, { path: "/admin/dashboard", element: _jsx(AdminDashboardPage, {}) }), _jsx(Route, { path: "/admin/users", element: _jsx(AdminUsersPage, {}) }), _jsx(Route, { path: "/admin/templates", element: _jsx(AdminTemplatesPage, {}) }), _jsx(Route, { path: "/admin/analytics", element: _jsx(AdminAnalyticsPage, {}) })] }) }), _jsx(Route, { path: "*", element: _jsx(NotFoundPage, {}) })] })); };
export default App;
